import type { App, Plugin } from 'vue'
import { makeInstaller } from '@alkaid-plus/utils'

// 导出所有组件
export * from '@alkaid-plus/components'

// 导出所有 hooks
export * from '@alkaid-plus/hooks'

// 导出所有工具函数
export * from '@alkaid-plus/utils'

// 导入所有组件用于全量注册
import {
  AkButton,
  AkButtonGroup,
  AkIcon,
  AkLink,
  AkScrollbar,
  AkSpace,
  AkText,
  AkInput,
  AkInputNumber,
  AkSelect,
  AkOption,
  AkOptionGroup,
  AkCascader,
  AkCheckbox,
  AkCheckboxButton,
  AkCheckboxGroup,
  AkRadio,
  AkRadioButton,
  AkRadioGroup,
  AkSwitch,
  AkDatePicker,
  AkTimePicker,
  AkTimeSelect,
  AkColorPicker,
  AkRate,
  AkSlider,
  AkUpload,
  AkForm,
  AkFormItem,
  AkAutocomplete,
  AkTable,
  AkTableColumn,
  AkTag,
  AkProgress,
  AkTree,
  AkPagination,
  AkBadge,
  AkAvatar,
  AkSkeleton,
  AkSkeletonItem,
  AkEmpty,
  AkDescriptions,
  AkDescriptionsItem,
  AkResult,
  AkStatistic,
  AkCountdown,
  AkMenu,
  AkMenuItem,
  AkMenuItemGroup,
  AkSubMenu,
  AkTabs,
  AkTabPane,
  AkBreadcrumb,
  AkBreadcrumbItem,
  AkDropdown,
  AkDropdownMenu,
  AkDropdownItem,
  AkSteps,
  AkStep,
  AkPageHeader,
  AkAlert,
  AkDialog,
  AkDrawer,
  AkPopconfirm,
  AkPopover,
  AkTooltip,
  AkContainer,
  AkHeader,
  AkAside,
  AkMain,
  AkFooter,
  AkRow,
  AkCol,
  AkDivider,
  AkCard,
  AkCollapse,
  AkCollapseItem,
  AkAffix,
  AkBacktop,
  AkCalendar,
  AkCarousel,
  AkCarouselItem,
  AkImage,
  AkImageViewer,
  AkTimeline,
  AkTimelineItem,
  AkTransfer,
  AkTreeSelect,
  AkTableV2,
  AkWatermark,
  AkTour,
  AkTourStep,
  AkAnchor,
  AkAnchorLink,
  AkSegmented,
  AkMention,
} from '@alkaid-plus/components'

// 所有组件列表
const components: Plugin[] = [
  AkButton,
  AkButtonGroup,
  AkIcon,
  AkLink,
  AkScrollbar,
  AkSpace,
  AkText,
  AkInput,
  AkInputNumber,
  AkSelect,
  AkOption,
  AkOptionGroup,
  AkCascader,
  AkCheckbox,
  AkCheckboxButton,
  AkCheckboxGroup,
  AkRadio,
  AkRadioButton,
  AkRadioGroup,
  AkSwitch,
  AkDatePicker,
  AkTimePicker,
  AkTimeSelect,
  AkColorPicker,
  AkRate,
  AkSlider,
  AkUpload,
  AkForm,
  AkFormItem,
  AkAutocomplete,
  AkTable,
  AkTableColumn,
  AkTag,
  AkProgress,
  AkTree,
  AkPagination,
  AkBadge,
  AkAvatar,
  AkSkeleton,
  AkSkeletonItem,
  AkEmpty,
  AkDescriptions,
  AkDescriptionsItem,
  AkResult,
  AkStatistic,
  AkCountdown,
  AkMenu,
  AkMenuItem,
  AkMenuItemGroup,
  AkSubMenu,
  AkTabs,
  AkTabPane,
  AkBreadcrumb,
  AkBreadcrumbItem,
  AkDropdown,
  AkDropdownMenu,
  AkDropdownItem,
  AkSteps,
  AkStep,
  AkPageHeader,
  AkAlert,
  AkDialog,
  AkDrawer,
  AkPopconfirm,
  AkPopover,
  AkTooltip,
  AkContainer,
  AkHeader,
  AkAside,
  AkMain,
  AkFooter,
  AkRow,
  AkCol,
  AkDivider,
  AkCard,
  AkCollapse,
  AkCollapseItem,
  AkAffix,
  AkBacktop,
  AkCalendar,
  AkCarousel,
  AkCarouselItem,
  AkImage,
  AkImageViewer,
  AkTimeline,
  AkTimelineItem,
  AkTransfer,
  AkTreeSelect,
  AkTableV2,
  AkWatermark,
  AkTour,
  AkTourStep,
  AkAnchor,
  AkAnchorLink,
  AkSegmented,
  AkMention,
]

// 创建安装器
const installer = makeInstaller(components)

// 默认导出
export default installer

// 版本信息
export const version = '1.0.0'

/**
 * 全量安装 Alkaid Plus
 *
 * @example
 * ```ts
 * import { createApp } from 'vue'
 * import AlkaidPlus from 'alkaid-plus'
 * import 'alkaid-plus/dist/index.css'
 *
 * const app = createApp(App)
 * app.use(AlkaidPlus)
 * ```
 */
export const install = installer.install
