export const componentList = [
  {
    name: 'Button',
    kebabName: 'button',
    path: './button',
    category: 'Basic',
    docTitle: 'Button 按钮',
    exportNames: ['AkButton', 'AkButtonGroup'],
  },
  {
    name: 'Icon',
    kebabName: 'icon',
    path: './icon',
    category: 'Basic',
    docTitle: 'Icon 图标',
    exportNames: ['AkIcon'],
  },
  {
    name: 'Link',
    kebabName: 'link',
    path: './link',
    category: 'Basic',
    docTitle: 'Link 链接',
    exportNames: ['AkLink'],
  },
  {
    name: 'Scrollbar',
    kebabName: 'scrollbar',
    path: './scrollbar',
    category: 'Basic',
    docTitle: 'Scrollbar 滚动条',
    exportNames: ['AkScrollbar'],
  },
  {
    name: 'Space',
    kebabName: 'space',
    path: './space',
    category: 'Basic',
    docTitle: 'Space 间距',
    exportNames: ['AkSpace'],
  },
  {
    name: 'Text',
    kebabName: 'text',
    path: './text',
    category: 'Basic',
    docTitle: 'Text 文本',
    exportNames: ['AkText'],
  },

  {
    name: 'Input',
    kebabName: 'input',
    path: './input',
    category: 'Form',
    docTitle: 'Input 输入框',
    exportNames: ['AkInput'],
  },
  {
    name: 'InputNumber',
    kebabName: 'input-number',
    path: './input-number',
    category: 'Form',
    docTitle: 'InputNumber 数字输入框',
    exportNames: ['AkInputNumber'],
  },
  {
    name: 'Select',
    kebabName: 'select',
    path: './select',
    category: 'Form',
    docTitle: 'Select 选择器',
    exportNames: ['AkSelect', 'AkOption', 'AkOptionGroup'],
  },
  {
    name: 'Cascader',
    kebabName: 'cascader',
    path: './cascader',
    category: 'Form',
    docTitle: 'Cascader 级联选择器',
    exportNames: ['AkCascader'],
  },
  {
    name: 'Checkbox',
    kebabName: 'checkbox',
    path: './checkbox',
    category: 'Form',
    docTitle: 'Checkbox 多选框',
    exportNames: ['AkCheckbox', 'AkCheckboxButton', 'AkCheckboxGroup'],
  },
  {
    name: 'Radio',
    kebabName: 'radio',
    path: './radio',
    category: 'Form',
    docTitle: 'Radio 单选框',
    exportNames: ['AkRadio', 'AkRadioButton', 'AkRadioGroup'],
  },
  {
    name: 'Switch',
    kebabName: 'switch',
    path: './switch',
    category: 'Form',
    docTitle: 'Switch 开关',
    exportNames: ['AkSwitch'],
  },
  {
    name: 'DatePicker',
    kebabName: 'date-picker',
    path: './date-picker',
    category: 'Form',
    docTitle: 'DatePicker 日期选择器',
    exportNames: ['AkDatePicker'],
  },
  {
    name: 'TimePicker',
    kebabName: 'time-picker',
    path: './time-picker',
    category: 'Form',
    docTitle: 'TimePicker 时间选择器',
    exportNames: ['AkTimePicker', 'AkTimeSelect'],
    subComponents: {
      AkTimeSelect: 'time-select',
    },
  },
  {
    name: 'ColorPicker',
    kebabName: 'color-picker',
    path: './color-picker',
    category: 'Form',
    docTitle: 'ColorPicker 颜色选择器',
    exportNames: ['AkColorPicker'],
  },
  {
    name: 'Rate',
    kebabName: 'rate',
    path: './rate',
    category: 'Form',
    docTitle: 'Rate 评分',
    exportNames: ['AkRate'],
  },
  {
    name: 'Slider',
    kebabName: 'slider',
    path: './slider',
    category: 'Form',
    docTitle: 'Slider 滑块',
    exportNames: ['AkSlider'],
  },
  {
    name: 'Upload',
    kebabName: 'upload',
    path: './upload',
    category: 'Form',
    docTitle: 'Upload 上传',
    exportNames: ['AkUpload'],
  },
  {
    name: 'Form',
    kebabName: 'form',
    path: './form',
    category: 'Form',
    docTitle: 'Form 表单',
    exportNames: ['AkForm', 'AkFormItem'],
  },
  {
    name: 'Autocomplete',
    kebabName: 'autocomplete',
    path: './autocomplete',
    category: 'Form',
    docTitle: 'Autocomplete 自动完成',
    exportNames: ['AkAutocomplete'],
  },

  {
    name: 'Table',
    kebabName: 'table',
    path: './table',
    category: 'Data',
    docTitle: 'Table 表格',
    exportNames: ['AkTable', 'AkTableColumn'],
  },
  {
    name: 'Tag',
    kebabName: 'tag',
    path: './tag',
    category: 'Data',
    docTitle: 'Tag 标签',
    exportNames: ['AkTag'],
  },
  {
    name: 'Progress',
    kebabName: 'progress',
    path: './progress',
    category: 'Data',
    docTitle: 'Progress 进度条',
    exportNames: ['AkProgress'],
  },
  {
    name: 'Tree',
    kebabName: 'tree',
    path: './tree',
    category: 'Data',
    docTitle: 'Tree 树形控件',
    exportNames: ['AkTree'],
  },
  {
    name: 'Pagination',
    kebabName: 'pagination',
    path: './pagination',
    category: 'Data',
    docTitle: 'Pagination 分页',
    exportNames: ['AkPagination'],
  },
  {
    name: 'Badge',
    kebabName: 'badge',
    path: './badge',
    category: 'Data',
    docTitle: 'Badge 徽章',
    exportNames: ['AkBadge'],
  },
  {
    name: 'Avatar',
    kebabName: 'avatar',
    path: './avatar',
    category: 'Data',
    docTitle: 'Avatar 头像',
    exportNames: ['AkAvatar'],
  },
  {
    name: 'Skeleton',
    kebabName: 'skeleton',
    path: './skeleton',
    category: 'Data',
    docTitle: 'Skeleton 骨架屏',
    exportNames: ['AkSkeleton', 'AkSkeletonItem'],
  },
  {
    name: 'Empty',
    kebabName: 'empty',
    path: './empty',
    category: 'Data',
    docTitle: 'Empty 空状态',
    exportNames: ['AkEmpty'],
  },
  {
    name: 'Descriptions',
    kebabName: 'descriptions',
    path: './descriptions',
    category: 'Data',
    docTitle: 'Descriptions 描述列表',
    exportNames: ['AkDescriptions', 'AkDescriptionsItem'],
  },
  {
    name: 'Result',
    kebabName: 'result',
    path: './result',
    category: 'Data',
    docTitle: 'Result 结果',
    exportNames: ['AkResult'],
  },
  {
    name: 'Statistic',
    kebabName: 'statistic',
    path: './statistic',
    category: 'Data',
    docTitle: 'Statistic 统计数值',
    exportNames: ['AkStatistic', 'AkCountdown'],
  },

  {
    name: 'Menu',
    kebabName: 'menu',
    path: './menu',
    category: 'Navigation',
    docTitle: 'Menu 菜单',
    exportNames: ['AkMenu', 'AkMenuItem', 'AkMenuItemGroup', 'AkSubMenu'],
  },
  {
    name: 'Tabs',
    kebabName: 'tabs',
    path: './tabs',
    category: 'Navigation',
    docTitle: 'Tabs 标签页',
    exportNames: ['AkTabs', 'AkTabPane'],
  },
  {
    name: 'Breadcrumb',
    kebabName: 'breadcrumb',
    path: './breadcrumb',
    category: 'Navigation',
    docTitle: 'Breadcrumb 面包屑',
    exportNames: ['AkBreadcrumb', 'AkBreadcrumbItem'],
  },
  {
    name: 'Dropdown',
    kebabName: 'dropdown',
    path: './dropdown',
    category: 'Navigation',
    docTitle: 'Dropdown 下拉菜单',
    exportNames: ['AkDropdown', 'AkDropdownMenu', 'AkDropdownItem'],
  },
  {
    name: 'Steps',
    kebabName: 'steps',
    path: './steps',
    category: 'Navigation',
    docTitle: 'Steps 步骤条',
    exportNames: ['AkSteps', 'AkStep'],
  },
  {
    name: 'PageHeader',
    kebabName: 'page-header',
    path: './page-header',
    category: 'Navigation',
    docTitle: 'PageHeader 页头',
    exportNames: ['AkPageHeader'],
  },

  {
    name: 'Alert',
    kebabName: 'alert',
    path: './alert',
    category: 'Feedback',
    docTitle: 'Alert 提示',
    exportNames: ['AkAlert'],
  },
  {
    name: 'Dialog',
    kebabName: 'dialog',
    path: './dialog',
    category: 'Feedback',
    docTitle: 'Dialog 对话框',
    exportNames: ['AkDialog'],
  },
  {
    name: 'Drawer',
    kebabName: 'drawer',
    path: './drawer',
    category: 'Feedback',
    docTitle: 'Drawer 抽屉',
    exportNames: ['AkDrawer'],
  },
  {
    name: 'Message',
    kebabName: 'message',
    path: './message',
    category: 'Feedback',
    docTitle: 'Message 消息提示',
    exportNames: ['AkMessage'],
    isPlugin: true,
  },
  {
    name: 'MessageBox',
    kebabName: 'message-box',
    path: './message-box',
    category: 'Feedback',
    docTitle: 'MessageBox 弹框',
    exportNames: ['AkMessageBox'],
    isPlugin: true,
  },
  {
    name: 'Notification',
    kebabName: 'notification',
    path: './notification',
    category: 'Feedback',
    docTitle: 'Notification 通知',
    exportNames: ['AkNotification'],
    isPlugin: true,
  },
  {
    name: 'Loading',
    kebabName: 'loading',
    path: './loading',
    category: 'Feedback',
    docTitle: 'Loading 加载',
    exportNames: ['AkLoading', 'AkLoadingDirective'],
    isPlugin: true,
  },
  {
    name: 'Popconfirm',
    kebabName: 'popconfirm',
    path: './popconfirm',
    category: 'Feedback',
    docTitle: 'Popconfirm 气泡确认框',
    exportNames: ['AkPopconfirm'],
  },
  {
    name: 'Popover',
    kebabName: 'popover',
    path: './popover',
    category: 'Feedback',
    docTitle: 'Popover 气泡卡片',
    exportNames: ['AkPopover'],
  },
  {
    name: 'Tooltip',
    kebabName: 'tooltip',
    path: './tooltip',
    category: 'Feedback',
    docTitle: 'Tooltip 文字提示',
    exportNames: ['AkTooltip'],
  },

  {
    name: 'Container',
    kebabName: 'container',
    path: './container',
    category: 'Layout',
    docTitle: 'Container 布局容器',
    exportNames: ['AkContainer', 'AkHeader', 'AkAside', 'AkMain', 'AkFooter'],
  },
  {
    name: 'Row',
    kebabName: 'row',
    path: './row',
    category: 'Layout',
    docTitle: 'Row 布局行',
    exportNames: ['AkRow'],
  },
  {
    name: 'Col',
    kebabName: 'col',
    path: './col',
    category: 'Layout',
    docTitle: 'Col 布局列',
    exportNames: ['AkCol'],
  },
  {
    name: 'Divider',
    kebabName: 'divider',
    path: './divider',
    category: 'Layout',
    docTitle: 'Divider 分割线',
    exportNames: ['AkDivider'],
  },
  {
    name: 'Card',
    kebabName: 'card',
    path: './card',
    category: 'Layout',
    docTitle: 'Card 卡片',
    exportNames: ['AkCard'],
  },
  {
    name: 'Collapse',
    kebabName: 'collapse',
    path: './collapse',
    category: 'Layout',
    docTitle: 'Collapse 折叠面板',
    exportNames: ['AkCollapse', 'AkCollapseItem'],
  },

  {
    name: 'Affix',
    kebabName: 'affix',
    path: './affix',
    category: 'Others',
    docTitle: 'Affix 固钉',
    exportNames: ['AkAffix'],
  },
  {
    name: 'Backtop',
    kebabName: 'backtop',
    path: './backtop',
    category: 'Others',
    docTitle: 'Backtop 回到顶部',
    exportNames: ['AkBacktop'],
  },
  {
    name: 'Calendar',
    kebabName: 'calendar',
    path: './calendar',
    category: 'Others',
    docTitle: 'Calendar 日历',
    exportNames: ['AkCalendar'],
  },
  {
    name: 'Carousel',
    kebabName: 'carousel',
    path: './carousel',
    category: 'Others',
    docTitle: 'Carousel 走马灯',
    exportNames: ['AkCarousel', 'AkCarouselItem'],
  },
  {
    name: 'Image',
    kebabName: 'image',
    path: './image',
    category: 'Others',
    docTitle: 'Image 图片',
    exportNames: ['AkImage', 'AkImageViewer'],
  },
  {
    name: 'InfiniteScroll',
    kebabName: 'infinite-scroll',
    path: './infinite-scroll',
    category: 'Others',
    docTitle: 'InfiniteScroll 无限滚动',
    exportNames: ['AkInfiniteScroll'],
  },
  {
    name: 'Timeline',
    kebabName: 'timeline',
    path: './timeline',
    category: 'Others',
    docTitle: 'Timeline 时间线',
    exportNames: ['AkTimeline', 'AkTimelineItem'],
  },
  {
    name: 'Transfer',
    kebabName: 'transfer',
    path: './transfer',
    category: 'Others',
    docTitle: 'Transfer 穿梭框',
    exportNames: ['AkTransfer'],
  },
  {
    name: 'TreeSelect',
    kebabName: 'tree-select',
    path: './tree-select',
    category: 'Others',
    docTitle: 'TreeSelect 树形选择',
    exportNames: ['AkTreeSelect'],
  },
  {
    name: 'VirtualizedTable',
    kebabName: 'virtualized-table',
    path: './virtualized-table',
    category: 'Others',
    docTitle: 'VirtualizedTable 虚拟表格',
    exportNames: ['AkTableV2'],
  },
  {
    name: 'Watermark',
    kebabName: 'watermark',
    path: './watermark',
    category: 'Others',
    docTitle: 'Watermark 水印',
    exportNames: ['AkWatermark'],
  },
  {
    name: 'Tour',
    kebabName: 'tour',
    path: './tour',
    category: 'Others',
    docTitle: 'Tour 漫游式引导',
    exportNames: ['AkTour', 'AkTourStep'],
  },
  {
    name: 'Anchor',
    kebabName: 'anchor',
    path: './anchor',
    category: 'Others',
    docTitle: 'Anchor 锚点',
    exportNames: ['AkAnchor', 'AkAnchorLink'],
  },
  {
    name: 'Segmented',
    kebabName: 'segmented',
    path: './segmented',
    category: 'Others',
    docTitle: 'Segmented 分段控制器',
    exportNames: ['AkSegmented'],
  },
  {
    name: 'Mention',
    kebabName: 'mention',
    path: './mention',
    category: 'Others',
    docTitle: 'Mention 提及',
    exportNames: ['AkMention'],
  },
]

export const directiveList = [
  {
    name: 'Loading',
    kebabName: 'loading',
    path: './loading',
  },
  {
    name: 'InfiniteScroll',
    kebabName: 'infinite-scroll',
    path: './infinite-scroll',
  },
]

export const categoryLabels = {
  Basic: 'Basic 基础组件',
  Form: 'Form 表单组件',
  Data: 'Data 数据展示',
  Navigation: 'Navigation 导航',
  Feedback: 'Feedback 反馈',
  Layout: 'Layout 布局',
  Others: 'Others 其他',
}
