/**
 * Alkaid Plus — Code generator
 *
 * Reads scripts/components.manifest.ts (the single source of truth) and
 * generates every file that previously required manual synchronization:
 *
 *   1. packages/components/src/index.ts
 *   2. packages/alkaid-plus/src/components.generated.ts
 *   3. packages/alkaid-plus/global.d.ts
 *   4. packages/resolver/src/component-map.generated.ts
 *   5. frontend-docs/.vitepress/components.generated.mts
 *
 * Run with: `pnpm codegen`
 * Auto-run by `pnpm gen <Name>` after scaffolding a new component.
 */

import { writeFileSync, mkdirSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'
import {
  components,
  directives,
  CATEGORY_LABELS,
  CATEGORY_ORDER,
  type ComponentEntry,
  type ComponentCategory,
} from './components.manifest.ts'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(__dirname, '..')

// ─── helpers ────────────────────────────────────────────────────────────────

const banner = '// AUTO-GENERATED by scripts/codegen.ts — DO NOT EDIT BY HAND\n'

/** Collect all (Ak-prefixed) public component names that should be registered/installed. */
function installableNames(entries: ComponentEntry[]): string[] {
  const names: string[] = []
  for (const e of entries) {
    if (e.kind === 'directive') continue
    names.push(e.name)
    if (e.subComponents) {
      for (const sub of e.subComponents) {
        if (!sub.name.includes('With')) names.push(sub.name)
      }
    }
  }
  return names
}

/** Build the resolver component-map: { AkName: elStyleKey } */
function buildResolverMap(entries: ComponentEntry[]): Record<string, string> {
  const map: Record<string, string> = {}
  for (const e of entries) {
    if (e.kind === 'directive') continue
    const parentKey = e.elStyleKey ?? e.folder
    map[e.name] = parentKey
    if (e.subComponents) {
      for (const sub of e.subComponents) {
        if (sub.name.includes('With')) continue
        map[sub.name] = sub.elStyleKey ?? parentKey
      }
    }
  }
  return map
}

/** Group components by category, preserving CATEGORY_ORDER */
function groupByCategory(entries: ComponentEntry[]) {
  const groups = new Map<ComponentCategory, ComponentEntry[]>()
  for (const cat of CATEGORY_ORDER) groups.set(cat, [])
  for (const e of entries) {
    groups.get(e.category)!.push(e)
  }
  return groups
}

// ─── 1. packages/components/src/index.ts ────────────────────────────────────
function genComponentsBarrel(): string {
  const groups = groupByCategory(components)
  const lines: string[] = [
    banner,
    '// Alkaid Plus Components — barrel exports grouped by category',
    '// 基于 Element Plus 的二次封装组件库',
    '',
  ]
  for (const cat of CATEGORY_ORDER) {
    const entries = groups.get(cat)!
    if (entries.length === 0) continue
    lines.push(`// ${CATEGORY_LABELS[cat]}`)
    for (const e of entries) {
      lines.push(`export * from './${e.folder}'`)
    }
    lines.push('')
  }
  return lines.join('\n')
}

// ─── 2. packages/alkaid-plus/src/components.generated.ts ────────────────────
function genAlkaidComponents(): string {
  const names = installableNames(components)
  const importLines = names.map((n) => `  ${n},`).join('\n')
  const arrayLines = names.map((n) => `  ${n},`).join('\n')
  return `${banner}
import type { Plugin } from 'vue'

// Re-export everything for type side-effects
export * from '@alkaid-plus/components'

// Named imports used by the installer
import {
${importLines}
} from '@alkaid-plus/components'

// Flat list of installable plugins (main components + sub-components)
export const allComponents: Plugin[] = [
${arrayLines}
]
`
}

// ─── 3. packages/alkaid-plus/global.d.ts ────────────────────────────────────
function genGlobalDts(): string {
  const names = installableNames(components)
  const importLines = names.map((n) => `  ${n},`).join('\n')
  const gcLines = names.map((n) => `    ${n}: typeof ${n}`).join('\n')
  return `${banner}
// Alkaid Plus Global Type Definitions
// IDE type-augmentation for <AkXxx /> tags in templates

import type {
${importLines}
} from 'alkaid-plus'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
${gcLines}
  }
}

export {}
`
}

// ─── 4. packages/resolver/src/component-map.generated.ts ────────────────────
function genResolverMap(): string {
  const map = buildResolverMap(components)
  const dirMap: Record<string, { importName: string; elStyleKey: string }> = {}
  for (const d of directives) {
    dirMap[d.name] = { importName: d.importName, elStyleKey: d.elStyleKey }
  }

  const mapLines = Object.entries(map)
    .map(([k, v]) => `  ${k}: '${v}',`)
    .join('\n')
  const dirLines = Object.entries(dirMap)
    .map(
      ([k, v]) =>
        `  ${k}: { importName: '${v.importName}', elStyleKey: '${v.elStyleKey}' },`
    )
    .join('\n')

  return `${banner}
/**
 * Auto-generated component → Element Plus style key map.
 * Consumed by ../index.ts (AkResolver / AkDirectiveResolver).
 */

export const componentMap: Record<string, string> = {
${mapLines}
}

export interface DirectiveMeta {
  importName: string
  elStyleKey: string
}

export const directiveMap: Record<string, DirectiveMeta> = {
${dirLines}
}
`
}

// ─── 5. frontend-docs/.vitepress/components.generated.mts ───────────────────
function genDocsSidebar(): string {
  const groups = groupByCategory(components)
  const sections: string[] = []
  for (const cat of CATEGORY_ORDER) {
    const entries = groups.get(cat)!.filter((e) => e.docs?.label)
    if (entries.length === 0) continue
    const items = entries
      .map(
        (e) =>
          `    { text: '${e.docs!.label}', link: '/components/${e.folder}' },`
      )
      .join('\n')
    sections.push(`  {
    text: '${CATEGORY_LABELS[cat]}',
    items: [
${items}
    ],
  },`)
  }
  return `${banner}
/**
 * Auto-generated VitePress sidebar entries for the /components/ section.
 * Imported by ../config.mts.
 */

import type { DefaultTheme } from 'vitepress'

export const componentSidebar: DefaultTheme.SidebarItem[] = [
${sections.join('\n')}
]
`
}

// ─── main ───────────────────────────────────────────────────────────────────
const files: Array<[string, string]> = [
  [resolve(ROOT, 'packages/components/src/index.ts'), genComponentsBarrel()],
  [
    resolve(ROOT, 'packages/alkaid-plus/src/components.generated.ts'),
    genAlkaidComponents(),
  ],
  [resolve(ROOT, 'packages/alkaid-plus/global.d.ts'), genGlobalDts()],
  [
    resolve(ROOT, 'packages/resolver/src/component-map.generated.ts'),
    genResolverMap(),
  ],
  [
    resolve(ROOT, 'frontend-docs/.vitepress/components.generated.mts'),
    genDocsSidebar(),
  ],
]

for (const [p, content] of files) {
  mkdirSync(dirname(p), { recursive: true })
  writeFileSync(p, content, 'utf-8')
  const rel = p.replace(ROOT + '/', '')
  console.log(`  ✔ ${rel}`)
}

console.log(`\n✅ Codegen complete. ${files.length} files written.`)
